In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [41]:
M = np.array([[0,1,1,0,0,0],
             [1,0,0,1,1,0],
             [1,0,0,1,0,0],
             [0,1,1,0,10,0],
             [0,1,0,1,0,1],
             [0,0,0,0,1,0]])
fusion = np.array([0,0,0,0,0,0])

P = M/(np.sum(M)/2)

M_1d = M.flatten()
sommets = np.arange()
P = M_1d/(np.sum(M_1d))

np.random.choice(M_1d,size=1, p=P)

array([10])

In [42]:
for i in range(100):
    print(np.random.choice(M_1d,size=1, p=P))

[1]
[1]
[10]
[1]
[10]
[1]
[1]
[1]
[10]
[10]
[10]
[1]
[1]
[1]
[1]
[1]
[10]
[1]
[10]
[10]
[10]
[1]
[10]
[10]
[1]
[1]
[1]
[1]
[10]
[1]
[10]
[1]
[1]
[1]
[10]
[10]
[10]
[1]
[1]
[1]
[10]
[1]
[10]
[1]
[1]
[1]
[10]
[10]
[1]
[1]
[10]
[1]
[1]
[1]
[10]
[1]
[10]
[1]
[1]
[1]
[10]
[10]
[10]
[10]
[1]
[10]
[1]
[10]
[1]
[1]
[1]
[1]
[1]
[1]
[10]
[10]
[1]
[10]
[1]
[10]
[1]
[10]
[10]
[1]
[1]
[1]
[1]
[1]
[10]
[10]
[1]
[1]
[1]
[1]
[10]
[10]
[1]
[1]
[1]
[1]


In [ ]:
def pick_edge(M, P):
    # Picks an edge e from graph M with a probability P
    

In [15]:
q = np.random.random((10,10))
print(q)
np.sort(q,axis=1)[:,-2:]

[[0.95326714 0.29517094 0.1527761  0.55236323 0.48922544 0.608497
  0.04582747 0.98590593 0.76894684 0.15217468]
 [0.95560051 0.98526262 0.42656365 0.73448    0.13555184 0.89144646
  0.4203386  0.38605932 0.353013   0.65408223]
 [0.57409501 0.53513177 0.03437798 0.53069556 0.6534067  0.10892506
  0.32796395 0.83854348 0.35269145 0.26365044]
 [0.17251769 0.56298526 0.2821338  0.32633858 0.68637214 0.30912894
  0.64055995 0.39163427 0.68979584 0.51675271]
 [0.74688096 0.91297771 0.60293418 0.75864475 0.66663942 0.26783239
  0.00236877 0.76054364 0.53058842 0.16883954]
 [0.16014049 0.17814854 0.69256448 0.11645306 0.46030555 0.73343252
  0.13208177 0.65601944 0.87491908 0.75854443]
 [0.52515406 0.10865161 0.31634875 0.97998621 0.24653985 0.12042254
  0.91183099 0.93084151 0.52140122 0.98420847]
 [0.06371588 0.63503743 0.67507727 0.95361963 0.05292996 0.45616549
  0.28725081 0.38380109 0.60732165 0.13108612]
 [0.71309998 0.87027847 0.90121558 0.96699606 0.36839103 0.86652936
  0.73098494 0

array([[0.95326714, 0.98590593],
       [0.95560051, 0.98526262],
       [0.6534067 , 0.83854348],
       [0.68637214, 0.68979584],
       [0.76054364, 0.91297771],
       [0.75854443, 0.87491908],
       [0.97998621, 0.98420847],
       [0.67507727, 0.95361963],
       [0.90121558, 0.96699606],
       [0.85961937, 0.9517893 ]])

In [16]:
q = np.random.random((10,10))

def choice(row, n, replace=False):
    return np.random.choice(row, size=n, p=row/row.sum(), replace=replace)

np.apply_along_axis(func1d=choice, axis=1, arr=q, n=2)

array([[0.49398662, 0.97817391],
       [0.42404521, 0.59840277],
       [0.09837273, 0.20095082],
       [0.93822399, 0.48662803],
       [0.63301057, 0.74551808],
       [0.49032916, 0.86282928],
       [0.28022496, 0.29698011],
       [0.48155322, 0.3033339 ],
       [0.68007175, 0.61286921],
       [0.23545843, 0.55871078]])

In [ ]:
# Rajouter une ligne de fustion
# Tirage de l'arête aléatoire
# Fusion en temps lineaire et selectione en temps lineaire


# Sélection aléatoire d'une arête parmi m arêtes