In [26]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [166]:
M = np.array([[0,1,1,0,0,0],
              [1,0,0,1,1,0],
              [1,0,0,1,0,0],
              [0,1,1,0,1,0],
              [0,1,0,1,0,1],
              [0,0,0,0,1,0]])

fusion = [[] for i in range(M.shape[0])]

somme_ligne = np.sum(M,axis=1)
nb_arrete = np.sum(somme_ligne)


# Random choice
def arrete_choice(M, somme_ligne, nb_arrete) :
    
    random_arrete = np.random.randint(nb_arrete)
    print(random_arrete)
    print(somme_ligne)
    cumul = 0
    for i in range(len(somme_ligne)) :
        cumul += somme_ligne[i]
        if cumul > random_arrete :
            break
    
    j = random_arrete - (cumul - somme_ligne[i])
    cumul = 0
    for k in range(M.shape[1]) :
        cumul += M[i,k]
        if cumul > j :
            break
            

    return M[i,k],i,k

In [167]:
def fusionner(fusion,i,j) :
    if j not in fusion[i] :
        fusion[i].append(j)
    if fusion[j] != [] :
        for e in fusion[j] :
            fusionner(fusion,i,e)
    

In [168]:
def Karger(M) :
    fusion = [[] for i in range(M.shape[0])]
    somme_ligne = np.sum(M,axis=1)
    nb_arrete = np.sum(somme_ligne)
    
    while nb_arrete > 2 :
        val,i,j = arrete_choice(M, somme_ligne,nb_arrete)
        # Modifications
        nb_arrete -= val
        M[i,j], M[j,i] = 0, 0
        nv_fusion = [[] for i in range(len(fusion) -1)]

    return fusion

In [169]:
Karger(M)

2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
8
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
8
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2

[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3

5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2

[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3

[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3

1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3

[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3

5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2

7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2

5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2

5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2

[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3

[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3

1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2

2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2

[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3

7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2

3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2

1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2

[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3

KeyboardInterrupt: 

In [99]:
M_1D = []
for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        M_1D.append(M[i,j])
        #M_1D[i*M.shape[0]+j] = (M[i,j], (i,j))
        
M_1D = M.shape[0]*M.shape[1]

a = np.random.choice(np.arange(M_1D),size=1, p=np.ndarray.flatten(P))

i = a // M.shape[0]
j = a %  M.shape[0]

print(a)
print(i,j)

# M_1d = M.flatten()

# P = M_1D/(np.sum(M_1D))


[10]
[1] [4]


In [ ]:
for i in range(100):
    print(np.random.choice(M_1d,size=1, p=P))

In [ ]:
def pick_edge(M, P):
    # Picks an edge e from graph M with a probability P
    

In [ ]:
q = np.random.random((10,10))
print(q)
np.sort(q,axis=1)[:,-2:]

In [ ]:
q = np.random.random((10,10))

def choice(row, n, replace=False):
    return np.random.choice(row, size=n, p=row/row.sum(), replace=replace)

np.apply_along_axis(func1d=choice, axis=1, arr=q, n=2)

In [ ]:
# Rajouter une ligne de fustion
# Tirage de l'arête aléatoire
# Fusion en temps lineaire et selectione en temps lineaire


# Sélection aléatoire d'une arête parmi m arêtes