In [41]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [42]:
M = np.array([[0,1,1,0,0,0],
              [1,0,0,1,1,0],
              [1,0,0,1,0,0],
              [0,1,1,0,1,0],
              [0,1,0,1,0,1],
              [0,0,0,0,1,0]])

fusion = [[] for i in range(M.shape[0])]

somme_ligne = np.sum(M,axis=1)
nb_arrete = np.sum(somme_ligne)

In [43]:
# Random choice
def arrete_choice(M, somme_ligne, nb_arrete) :
    
    random_arrete = np.random.randint(nb_arrete)

    cumul = 0
    for i in range(len(somme_ligne)) :
        cumul += somme_ligne[i]
        if cumul > random_arrete :
            break
    
    j = random_arrete - (cumul - somme_ligne[i])
    
    cumul = 0
    for k in range(M.shape[1]) :
        cumul += M[i,k]
        if cumul > j :
            break
            

    return M[i,k],i,k

In [261]:
def Karger(M) :
    # Affichage de la liste résultante
    def print_fusion(fusion):
        for i in range(len(fusion)):
            if len(fusion[i])>0:
                print(fusion[i])
                
    
    A = M.copy()
    
    fusion = [[i] for i in range(A.shape[0])]
    fusion = [[] for i in range(A.shape[0])]
    
    somme_ligne = np.sum(A,axis=1)
    nb_arrete = np.sum(somme_ligne)
    
    nb_sommets = A.shape[0]
    while nb_sommets > 2 :
        
        nb_arrete = np.sum(somme_ligne)

        # Random choice of an edge e to be removed
        while True : 
            val,i,j = arrete_choice(A, somme_ligne,nb_arrete)
            if val>0:
                break
        print(val,i,j)
        
        # Modifications
        li = A[i,:]
        lj = A[j,:]
        ci = A[:,i]
        cj = A[:,j]
        
        A[i,:] = li + lj
        A[:,i] = ci + cj
        A[i,i] = 0
               
        A[j,:] = -1
        A[:,j] = -1
        
        
        for e in fusion[j]:
            fusion[i].append(e)
        fusion[i].append(j)
        fusion[j] = []
        """
        for e in fusion[j]:
            fusion[i].append(e)
        fusion[j] = []
        """
        
        somme_ligne[j] = 0
        somme_ligne[i] -= val
        
        nb_sommets-=1
        
    print_fusion(fusion)
    
    coupure = A[A>0][0]
    
    return fusion, coupure

In [262]:
niter = 1000
for k in range(niter):
    Karger(M)

1 3 1
1 0 3
2 4 0
1 4 5
[1, 3, 0, 5]
1 4 1
1 2 0
2 3 4
1 3 5
[0]
[1, 4, 5]
1 4 1
2 4 3
1 2 0


KeyboardInterrupt: 

---

In [4]:
import random, copy

#input can be any adjacency list in a text file
data = open("testCase.txt", "r")
G = {}
for line in data:
    lst = [int(s) for s in line.split()]  # creates a list for each line of text file
    G[lst[0]] = lst[1:]  # adds the list for one vertex to the entire adj list in G
    # The code that creates an adjacency list from a text file(lines 6-10) were done with help from online resources


def choose_random_key(G):
    a = random.choice(list(G.keys()))  # picks a random vertex
    b = random.choice(list(G[a]))  # picks a random edge in the adjacency list
    return a, b


def karger(G):
    length = []
    while len(G) > 2:
        a, b = choose_random_key(G)  # the nodes that are part of the random edge
        G[a].extend(G[b])  # copies all items
        for x in G[b]:
            G[x].remove(b)  # remove the other occurrences of b in adjacency list
            G[x].append(a)  # tell them to look at a instead
        while a in G[a]:
            G[a].remove(a)  # remove self loops
        del G[b]  # getting rid of the empty vertex from the adj list
    return len(G[a])  # length of either vertex is same so just picked a


def multipleKarger(iterations):
    i = 0
    count = 10000000000  # a very large number that isn't a possible mincut
    while i < iterations:
        data = copy.deepcopy(G)  # this way don't have to reread the txt file
        min_cut = karger(data)
        if min_cut < count:
            count = min_cut
        i = i + 1
    return count


print("Running Karger one time: ", multipleKarger(1))
print("Running Karger one time: ", multipleKarger(1))
print("Running Karger 100 times: ", multipleKarger(100))

Running Karger one time:  2
Running Karger one time:  3
Running Karger 100 times:  2


In [167]:
def fusionner(fusion,i,j) :
    if j not in fusion[i] :
        fusion[i].append(j)
    if fusion[j] != [] :
        for e in fusion[j] :
            fusionner(fusion,i,e)
    

In [ ]:
def contraction(M,i,j):
    

In [168]:
def Karger(M) :
    fusion = [[] for i in range(M.shape[0])]
    somme_ligne = np.sum(M,axis=1)
    nb_arrete = np.sum(somme_ligne)
    
    while nb_arrete > 2 :
        val,i,j = arrete_choice(M, somme_ligne,nb_arrete)
        # Modifications
        nb_arrete -= val
        M[i,j], M[j,i] = 0, 0
        nv_fusion = [[] for i in range(len(fusion) -1)]

    return fusion

In [169]:
Karger(M)

2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
8
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
8
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2

[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3

5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2

[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3

[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3

1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3

[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3

5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2

7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2

5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2

5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2

[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3

[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3

1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2

2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2

[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
2
[2 3 2 3

[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3

7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2

3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2

1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2

[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
1
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
7
[2 3 2 3 3 1]
6
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
0
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
3
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
5
[2 3 2 3 3 1]
2
[2 3 2 3 3 1]
4
[2 3 2 3 3 1]
7
[2 3 2 3

KeyboardInterrupt: 

In [99]:
M_1D = []
for i in range(M.shape[0]):
    for j in range(M.shape[1]):
        M_1D.append(M[i,j])
        #M_1D[i*M.shape[0]+j] = (M[i,j], (i,j))
        
M_1D = M.shape[0]*M.shape[1]

a = np.random.choice(np.arange(M_1D),size=1, p=np.ndarray.flatten(P))

i = a // M.shape[0]
j = a %  M.shape[0]

print(a)
print(i,j)

# M_1d = M.flatten()

# P = M_1D/(np.sum(M_1D))


[10]
[1] [4]


In [ ]:
for i in range(100):
    print(np.random.choice(M_1d,size=1, p=P))

In [ ]:
def pick_edge(M, P):
    # Picks an edge e from graph M with a probability P
    

In [ ]:
q = np.random.random((10,10))
print(q)
np.sort(q,axis=1)[:,-2:]

In [ ]:
q = np.random.random((10,10))

def choice(row, n, replace=False):
    return np.random.choice(row, size=n, p=row/row.sum(), replace=replace)

np.apply_along_axis(func1d=choice, axis=1, arr=q, n=2)

In [ ]:
# Rajouter une ligne de fustion
# Tirage de l'arête aléatoire
# Fusion en temps lineaire et selectione en temps lineaire


# Sélection aléatoire d'une arête parmi m arêtes